-- App-wide key-value settings (intelligence tier, Ollama URL, model name, etc.)
CREATE TABLE IF NOT EXISTS app_settings (
  key        TEXT PRIMARY KEY,
  value      TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Single-row user behavioral profile generated by Ollama analysis
CREATE TABLE IF NOT EXISTS user_profile (
  id                           TEXT PRIMARY KEY DEFAULT 'default',
  summary                      TEXT NOT NULL,
  strengths_json               TEXT,
  growth_areas_json            TEXT,
  work_style                   TEXT,
  model_used                   TEXT,
  session_count_at_computation INTEGER,
  computed_at                  TEXT NOT NULL DEFAULT (datetime('now'))
);
